#!/usr/bin/env bash
# build-amd64-experimental.sh — produce an amd64 image with the rp shadow-FS
# overlay applied, for verifying rp's FUSE bits work on x86 via Docker.
#
# SCOPE (deliberately narrow — this is a smoke-test tool, not a production
# path):
#   * Builds linux/amd64 only, via `docker buildx`.
#   * Includes rp-fuse + rp-init.sh + the overlay's fuse3/user/mountpoint
#     setup. Does NOT install any agent profile (no claude/opencode), no
#     /etc/rp/instructions compose, no caller-ownership probe.
#   * Lands the result in the local docker daemon. No push, no registry.
#
# Usage:
#   scripts/build-amd64-experimental.sh [--user <name>] [--strip-sudo] <base-image>
#
# Flags (mirror .rp/config.yaml semantics):
#   --user <name>    Container user. Defaults to coder (created fresh by the
#                    overlay). Set to an image-shipped user (e.g. node) to
#                    adopt that user instead.
#   --strip-sudo     Opt in to removing sudo grants for the configured user
#                    during build (ADR-0009). Default off: build fails if
#                    the user has any sudoers entry.
#
# Example:
#   scripts/build-amd64-experimental.sh debian:bookworm-slim
#   scripts/build-amd64-experimental.sh --user node --strip-sudo \
#       mcr.microsoft.com/devcontainers/javascript-node:22
#
# Requires: Docker Desktop with buildx (default on recent installs). The
# rp-fuse cross-compile + the user image work both run under buildx's
# linux/amd64 emulation — slow on Apple Silicon but doesn't need a real
# amd64 host.

set -euo pipefail

RP_USER=coder
STRIP_SUDO=0
BASE=""

while [ "$#" -gt 0 ]; do
    case "$1" in
        --user)
            shift
            [ "$#" -ge 1 ] || { echo "build-amd64-experimental: --user needs a value" >&2; exit 2; }
            RP_USER=$1
            shift
            ;;
        --strip-sudo)
            STRIP_SUDO=1
            shift
            ;;
        --help|-h)
            sed -n '2,30p' "$0" | sed 's/^# \{0,1\}//'
            exit 0
            ;;
        --*)
            echo "build-amd64-experimental: unknown flag $1" >&2
            exit 2
            ;;
        *)
            if [ -n "$BASE" ]; then
                echo "build-amd64-experimental: unexpected positional arg: $1" >&2
                exit 2
            fi
            BASE=$1
            shift
            ;;
    esac
done

if [ -z "$BASE" ]; then
    echo "usage: build-amd64-experimental.sh [--user <name>] [--strip-sudo] <base-image>" >&2
    echo "" >&2
    echo "Example: build-amd64-experimental.sh debian:bookworm-slim" >&2
    exit 2
fi

REPO_DIR=$(cd "$(dirname "$0")/.." && pwd)

if ! docker buildx version >/dev/null 2>&1; then
    echo "build-amd64-experimental: docker buildx not available; install Docker Desktop" >&2
    exit 1
fi

# Derive a filesystem-safe slug from the base image ref. mcr.../universal:linux
# → mcr-universal-linux. Used as a tag suffix so multiple bases coexist.
SLUG=$(echo "$BASE" \
    | tr '/' '-' \
    | tr ':' '-' \
    | tr '.' '-' \
    | sed 's/[^a-zA-Z0-9_-]//g' \
    | sed 's/^mcr-microsoft-com-//' \
    | sed 's/-devcontainers//')

# Append the user to the tag so node/coder variants of the same base
# coexist in the local daemon.
BASE_TAG="rp-base-amd64:experiment"
OUT_TAG="rp-amd64-experiment:${SLUG}-${RP_USER}"

# --- Stage 1: build rp-base for amd64 ----------------------------------
echo ">> [1/2] Building $BASE_TAG (linux/amd64) via buildx ..." >&2
docker buildx build \
    --platform linux/amd64 \
    -f "$REPO_DIR/Dockerfile.base" \
    -t "$BASE_TAG" \
    --load \
    "$REPO_DIR"

# --- Stage 2: generate minimal overlay Dockerfile + build it ------------
OVERLAY_CTX=$(mktemp -d -t rp-amd64-overlay.XXXXXX)
trap "rm -rf $OVERLAY_CTX" EXIT

{
cat <<EOF
# Auto-generated by build-amd64-experimental.sh. Do not edit.
# Mirrors the runtime overlay produced by scripts/build-project-image.sh
# but stripped of agent-profile bits (no install.sh, no instructions, no
# settings files). Used to smoke-test the FUSE shadow stack on amd64.
FROM $BASE
USER root
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends fuse3 \\
    && rm -rf /var/lib/apt/lists/*

RUN sed -i 's/^#user_allow_other/user_allow_other/' /etc/fuse.conf 2>/dev/null \\
    || echo 'user_allow_other' >> /etc/fuse.conf

# Container user. Either adopt an existing image user or create one fresh.
RUN id -u $RP_USER >/dev/null 2>&1 \\
    || useradd -m -s /bin/bash $RP_USER
RUN test "\$(id -u $RP_USER)" -ne 0 \\
    || (echo "rp-amd64-experiment: user '$RP_USER' is root, refusing" >&2; exit 1)
EOF

if [ "$STRIP_SUDO" -eq 1 ]; then
    cat <<EOF
# strip_sudo opt-in (ADR-0009). Removes every common sudo grant for the
# configured user. The post-strip sudoers grep below is the safety net.
RUN rm -f /etc/sudoers.d/${RP_USER} 2>/dev/null || true
RUN sed -i "/^${RP_USER}[[:space:]]/d" /etc/sudoers 2>/dev/null || true
RUN for sd in /etc/sudoers.d/*; do \\
        [ -f "\$sd" ] && sed -i "/^${RP_USER}[[:space:]]/d; /^%sudo[[:space:]]/d; /^%wheel[[:space:]]/d" "\$sd" 2>/dev/null || true; \\
    done; true
RUN gpasswd -d ${RP_USER} sudo 2>/dev/null || true
RUN gpasswd -d ${RP_USER} wheel 2>/dev/null || true
EOF
fi

cat <<EOF
RUN ! grep -rqE "(^|[[:space:]])${RP_USER}([[:space:]]|\$)" /etc/sudoers /etc/sudoers.d/ 2>/dev/null \\
    || (echo "rp-amd64-experiment: user '$RP_USER' has a sudoers entry, refusing" >&2; exit 1)

RUN mkdir -p /var/lib/rp/shadow /var/lib/rp/backing /workspace /workspace-real /usr/local/lib/rp \\
    && chmod 0700 /var/lib/rp \\
    && chown root:root /var/lib/rp /var/lib/rp/shadow /var/lib/rp/backing

# Pull rp-fuse + init script from the amd64 rp-base we just built.
COPY --from=$BASE_TAG /usr/local/bin/rp-fuse /usr/local/bin/rp-fuse
COPY --from=$BASE_TAG /usr/local/bin/rp-init.sh /usr/local/bin/rp-init.sh
COPY --from=$BASE_TAG /etc/rp/instructions/00-container.md /etc/rp/instructions/00-container.md
RUN chmod 0755 /usr/local/bin/rp-fuse /usr/local/bin/rp-init.sh

WORKDIR /workspace
USER $RP_USER
EOF
} > "$OVERLAY_CTX/Dockerfile"

if [ "${RP_DEBUG:-}" = "1" ]; then
    echo ">> generated overlay Dockerfile ↓↓↓" >&2
    sed 's/^/   /' "$OVERLAY_CTX/Dockerfile" >&2
    echo ">> ↑↑↑" >&2
fi

echo ">> [2/2] Building $OUT_TAG (FROM $BASE) via buildx ..." >&2
docker buildx build \
    --platform linux/amd64 \
    -f "$OVERLAY_CTX/Dockerfile" \
    -t "$OUT_TAG" \
    --load \
    "$OVERLAY_CTX"

cat >&2 <<MSG

----------------------------------------------------------------------
Built: $OUT_TAG (linux/amd64), in the local docker daemon.
  base:        $BASE
  user:        $RP_USER$([ "$STRIP_SUDO" -eq 1 ] && echo "  (strip_sudo applied)")

Smoke-test it with:

  mkdir -p /tmp/rp-amd64-probe
  docker run --rm -it \\
      --cap-add SYS_ADMIN \\
      --device /dev/fuse \\
      -v /tmp/rp-amd64-probe:/workspace-real \\
      $OUT_TAG \\
      /usr/local/bin/rp-init.sh

In another shell:
  docker exec -it -u $RP_USER <container-id> bash

Inside, /workspace is the FUSE-mediated mount. /var/lib/rp is the
root-only shadow store. .rp/shadow rules in /workspace-real are honored.
This image does NOT have any agent installed — it's a FUSE smoke test.
----------------------------------------------------------------------
MSG
